/**
 * Pulls the canonical facts out of the puravida CLI repo and writes them to
 * src/data/cli.json, which the site renders from. Run it in CI; commit the
 * result. The committed file is what builds read, so a network failure here can
 * never break a deploy — it can only leave the site one release behind, and the
 * scheduled run in .github/workflows/sync.yml catches that.
 *
 * Pinned to the latest *release* rather than to main: the site documents the
 * version people can actually install, not whatever is unreleased on the branch.
 */
import { writeFile, readFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

const REPO = 'mark-mcdermott/puravida'
const OUT = fileURLToPath(new URL('../src/data/cli.json', import.meta.url))

const token = process.env.GITHUB_TOKEN
const headers = {
  accept: 'application/vnd.github+json',
  ...(token ? { authorization: `Bearer ${token}` } : {}),
}

async function latestRef() {
  const res = await fetch(`https://api.github.com/repos/${REPO}/releases/latest`, { headers })
  if (!res.ok) {
    console.warn(`! releases/latest returned ${res.status} — falling back to main`)
    return 'main'
  }
  const { tag_name } = await res.json()
  return tag_name ?? 'main'
}

async function raw(ref, path) {
  const res = await fetch(`https://raw.githubusercontent.com/${REPO}/${ref}/${path}`)
  if (!res.ok) throw new Error(`fetch ${path}@${ref} failed: ${res.status}`)
  return res.text()
}

/** Text from a heading until the next heading of the same or higher level. */
function section(md, heading) {
  const re = new RegExp(`^(#{2,4})\\s+${heading}\\s*$`, 'im')
  const start = md.match(re)
  if (!start) throw new Error(`section "${heading}" not found — README structure changed`)
  const level = start[1].length
  const from = start.index + start[0].length
  const rest = md.slice(from)
  const next = rest.search(new RegExp(`^#{1,${level}}\\s+`, 'm'))
  return next === -1 ? rest : rest.slice(0, next)
}

/** Rows of a GitHub-flavoured markdown table, header and divider dropped. */
function table(text, heading) {
  const rows = text
    .split('\n')
    .filter((l) => l.trim().startsWith('|'))
    .map((l) =>
      l
        .trim()
        .replace(/^\||\|$/g, '')
        .split('|')
        .map((c) => c.trim()),
    )
    .filter((cells) => !cells.every((c) => /^:?-{2,}:?$/.test(c)))
  if (rows.length < 2) throw new Error(`no table under "${heading}" — README structure changed`)
  return rows.slice(1)
}

/** Contents of every fenced code block in a chunk of markdown. */
function fences(text) {
  return [...text.matchAll(/```[a-z]*\n([\s\S]*?)```/g)].map((m) => m[1].trimEnd())
}

async function main() {
  const ref = await latestRef()
  const [script, readme, changelog] = await Promise.all([
    raw(ref, 'puravida'),
    raw(ref, 'README.md'),
    raw(ref, 'CHANGELOG.md'),
  ])

  const version = script.match(/^VERSION="([^"]+)"/m)?.[1]
  if (!version) throw new Error('VERSION not found in the puravida script')

  const replaces = fences(section(readme, 'What it replaces'))
  if (replaces.length !== 4) {
    console.warn(`! expected 4 code blocks under "What it replaces", found ${replaces.length}`)
  }

  const data = {
    /** Generated by scripts/sync-cli.mjs — edit the CLI repo, not this file. */
    generatedAt: new Date().toISOString(),
    ref,
    version,
    repo: REPO,
    options: table(section(readme, 'Options'), 'Options').map(([flag, description]) => ({
      flag,
      description,
    })),
    exitCodes: table(section(readme, 'Exit status'), 'Exit status').map(([code, meaning]) => ({
      code: code.replace(/`/g, ''),
      meaning,
    })),
    usage: table(section(readme, 'Usage'), 'Usage').map(([command, creates]) => ({
      command: command.replace(/`/g, ''),
      creates,
    })),
    replaces: {
      beforeInline: replaces[0] ?? '',
      afterInline: replaces[1] ?? '',
      beforeHeredoc: replaces[2] ?? '',
      afterHeredoc: replaces[3] ?? '',
    },
    // "Unreleased" is a working heading, not a release — it has nothing a
    // visitor can install, so it never reaches the site.
    changelog: changelog
      .split(/^## /m)
      .slice(1)
      .map((entry) => {
        const [title, ...body] = entry.split('\n')
        return { title: title.trim(), body: body.join('\n').trim() }
      })
      .filter(({ title }) => !/^\[?unreleased/i.test(title))
      .slice(0, 3),
  }

  let previous = null
  try {
    previous = JSON.parse(await readFile(OUT, 'utf8'))
  } catch {
    /* first run */
  }

  // `generatedAt` changes on every run, so writing unconditionally would defeat
  // the workflow's "commit only if the CLI moved" guard and produce a junk
  // commit — and a production deploy — on every nightly cron. Compare the
  // meaningful content and leave the file alone when nothing actually moved.
  const withoutTimestamp = ({ generatedAt, ...rest }) => JSON.stringify(rest)
  if (previous && withoutTimestamp(previous) === withoutTimestamp(data)) {
    console.log(`= ${REPO}@${ref} still v${version} — cli.json unchanged, not rewriting`)
    return
  }

  await writeFile(OUT, `${JSON.stringify(data, null, 2)}\n`)
  const moved = previous && previous.version !== version
  console.log(
    `✓ synced ${REPO}@${ref} — v${version}, ${data.usage.length} usage rows, ` +
      `${data.options.length} options, ${data.exitCodes.length} exit codes` +
      (moved ? ` (was v${previous.version})` : ''),
  )
}

main().catch((err) => {
  console.error(`✗ sync failed: ${err.message}`)
  process.exit(1)
})
